# Generated by Django 4.2.2 on 2023-12-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditosusuario',
            name='historial',
            field=models.TextField(default='Sin historial'),
        ),
    ]
