# Generated by Django 4.2.2 on 2023-12-28 10:59

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuariopersonalizado'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuariopersonalizado',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='creditos',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='creditos'),
        ),
        migrations.DeleteModel(
            name='CreditosUsuario',
        ),
    ]
