# Generated by Django 4.2.2 on 2023-12-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='historial',
            field=models.TextField(blank=True, null=True, verbose_name='historial'),
        ),
    ]
