# Generated by Django 5.0.1 on 2024-02-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuariopersonalizado_historial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='historial',
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='historial',
            field=models.ManyToManyField(related_name='historial_entries', to='usuario.historialcredito'),
        ),
    ]
