# Generated by Django 5.0.1 on 2024-02-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_historialcredito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='historial',
        ),
        migrations.DeleteModel(
            name='HistorialCredito',
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='historial',
            field=models.TextField(blank=True, null=True, verbose_name='historial'),
        ),
    ]
